defmodule Huddlz.Repo.Migrations.AddCapacityToHuddlz do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:huddlz) do
      add :capacity, :bigint
    end
  end

  def down do
    alter table(:huddlz) do
      remove :capacity
    end
  end
end
